training_data_version: v7
skill_domains_version: v3
job_data_version: v4
activity_domains_version: v4
personas_info_data_version: v14
interview_data_version: v8
submission_version: v2
harmonized_skills_map_version: v1